IpoetryBundle\Entity\IpoetryUserCity:
    type: entity
    table: ipoetry_user_city
    id:
        ipoetryCityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ipoetry_city_id
            generator:
                strategy: IDENTITY
    fields:
        cityName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Название города'
                default: undefined
            column: city_name
    lifecycleCallbacks: {  }
