IpoetryBundle\Entity\IpoetryUserFollowers:
    type: entity
    table: ipoetry_user_followers
    id: {  }
    fields:
        ipoetryUserFollowersId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ipoetry_user_followers_id
        ipoetryUserUserParentId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ipoetry_user_user_parent_id
    oneToOne:
        ipoetryUserUser:
            targetEntity: IpoetryUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ipoetry_user_user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
