# AcmeDemoBundle routes (to be removed)
_demo:
    resource: '@AcmeDemoBundle/Resources/config/routing.yml'
    prefix: /demo

app:
    resource: '@AppBundle/Controller/'
    type:     annotation

IpoetryBundle:
    resource: '@IpoetryBundle/Resources/config/routing.yml'
