# AcmeDemoBundle routes (to be removed)
_demo:
    resource: '@AcmeDemoBundle/Resources/config/routing.yml'
    prefix: /demo

app:
    resource: '@AppBundle/Controller/'
    type:     annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /loginvk
    
IpoetryBundle:
    resource: '@IpoetryBundle/Resources/config/routing.yml'

vkontakte_loginvk:
    path: '@IpoetryBundle/loginvk/checkvk'
    defaults: { _controller: IpoetryBundle:LoginVk:checkvk }
